name: Request a new GitHub Organization
description: Request a new GitHub Organization
title: "New Organization request"
assignees:
  - rajbos
body:
  - type: markdown
    attributes:
      value: |
        Thanks you for your request. We need some information before we can proceed.
        After that, the request will be reviewed. Process tracking will happen inside this issue.

        Please tag '@-username' or '@-teamname' to notifiy them in comments.
  - type: input
    id: organization_name
    attributes:
      label: Organization Name
      description: The name that you would like your organization to have. It can consist of alphanumeric characters and single hyphens (-), must not start or end with a hyphen and must not be longer than 39 characters.
      placeholder: "my-new-organization"
    validations:
      required: true
  - type: input
    id: organization_display_name
    attributes:
      label: Organization Display Name
      description: If you would like your organization to have a display name that is different from the organization name, you can specify it here.
      placeholder: "My New Organization"
    validations:
      required: true
  - type: input
    id: organization_owner
    attributes:
      label: Organization Owner
      description: A user ID within GitHub. You can find the ID on the right top corner on your profile.
      placeholder: "firstname-lastname"
    validations:
      required: true
  - type: input
    id: organization_deputy
    attributes:
      label: Organization Deputy
      description: Another user ID who will be owner in your Organization. You can add owners later on as well. Set to false if you don't want a deputy right now.
      placeholder: "firstname-lastname"
  - type: checkboxes
    id: enterprise_runners
    attributes:
      label: Enterprise Runners
      description: When set to true, will attach shared enterprise runners to your organization for usage.
      options:
        - label: enable
  - type: dropdown
    id: business_unit
    attributes:
      label: Business Unit
      description: Specify your Business unit (BU).
      options:
        - DI FA
        - DI PA
        - DI MC
        - DI SW
        - DI CS
        - DI IT
        - SI EP
        - Evosoft
  - type: input
    id: acp-level
    attributes:
      label: ACP Level/BIA Rating
      description: Asset Classification & Protection (ACP) level or BIA (Business Impact Assessment). If not specified will use ACP rating 0.
      placeholder: "1-2-1"
  - type: dropdown
    id: estimated_users
    attributes:
      label: Estimated number of users
      description: Your estimated number of users within your organization who will be working in the GitHub Organization.
      options:
        - 1-10
        - 10-50
        - 50-200
        - 200-500
        - more than 500
  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Use
      description: By submitting this issue, you agree to follow our Terms of Use.
      options:
        - label: I agree to follow the Terms of Use
          required: true
